### ISSUE TITLE
Documentation Todo's

### ISSUE THREAD

**Issue by mborgerson** [angr/angr-management#1347]
### Description

- [ ] Architectures (or cross link to an angr page about it)
- [ ] Run analysis dialog info (describe what the options do)
- [ ] More view info
- [ ] Symbolic execution
- [ ] Keyboard shortcuts (some already listed on README.md)
- [ ] Decompilation options
- [ ] Plugins
   - [ ] Source viewer
   - [ ] Binsync
   - [ ] Binary diffing
- [ ] Patching
- [ ] Tracing
